"""Human-gated promote-to-live CLI — the ONLY code path that writes
strategy files in v2.

Flow: operator reads pending_live_promotion.jsonl, decides yes/no, runs:

    python -m pipeline.autoresearch.regime_autoresearch.scripts.promote_to_live \
        --rule-id P-xxxx

Writes the strategy file at
    pipeline/autoresearch/regime_autoresearch/generated/<rule_id>_strategy.py
appends a matching hypothesis-registry.jsonl entry, and COMMITS both in
a single git commit so the kill-switch pre-commit hook passes.

Refuses:
- rule-id absent from pending_live_promotion.jsonl
- rule not in state=FORWARD_SHADOW_PASS
"""
from __future__ import annotations

import argparse
import json
import subprocess
from datetime import datetime, timezone
from pathlib import Path

from pipeline.autoresearch.regime_autoresearch.constants import DATA_DIR


DEFAULT_PENDING_PATH = DATA_DIR / "pending_live_promotion.jsonl"
REGISTRY_PATH = Path("docs/superpowers/hypothesis-registry.jsonl")
GENERATED_DIR = (
    Path(__file__).resolve().parents[1] / "generated"
)


def _load_pending(path: Path) -> list[dict]:
    if not path.exists():
        return []
    return [
        json.loads(l) for l in path.read_text().splitlines() if l.strip()
    ]


def _write_strategy_file(rule: dict, rule_id: str) -> Path:
    GENERATED_DIR.mkdir(parents=True, exist_ok=True)
    path = GENERATED_DIR / f"{rule_id}_strategy.py"
    content = f'''"""Auto-generated by promote_to_live on {datetime.now(
        timezone.utc
    ).isoformat()}.

Rule: {rule_id}
Feature: {rule["feature"]}
Construction: {rule["construction_type"]}
k: {rule["threshold_value"]}
Hold: {rule["hold_horizon"]}
Regime: {rule["regime"]}
Forward Sharpe: {rule["forward_sharpe"]} (vs incumbent {rule["incumbent_sharpe"]})
"""
RULE_ID = "{rule_id}"
RULE = {json.dumps(rule, indent=2)}
'''
    path.write_text(content)
    return path


def _append_registry_entry(rule: dict, rule_id: str) -> None:
    entry = {
        "hypothesis_id": f"H-AUTORES-{rule_id}",
        "author": "autoresearch-v2-mode2",
        "date_registered": datetime.now(timezone.utc).date().isoformat(),
        "strategy_name": f"regime_autoresearch_{rule_id}",
        "strategy_class": "regime_conditional_cross_sectional",
        "description": (
            f"Rule promoted from v2 autoresearch engine; "
            f"feature={rule['feature']}, construction="
            f"{rule['construction_type']}, k={rule['threshold_value']}, "
            f"h={rule['hold_horizon']}, regime={rule['regime']}"
        ),
        "source_rule_id": rule_id,
        "forward_shadow_sharpe": rule["forward_sharpe"],
        "incumbent_sharpe": rule["incumbent_sharpe"],
        "status": "PROMOTED_LIVE",
        "standards_version": "1.0_2026-04-23",
    }
    REGISTRY_PATH.parent.mkdir(parents=True, exist_ok=True)
    with REGISTRY_PATH.open("a") as f:
        f.write(json.dumps(entry) + "\n")


def _git_commit(strategy_path: Path, rule_id: str) -> None:
    subprocess.check_call(["git", "add", "-f", str(strategy_path),
                           str(REGISTRY_PATH)])
    subprocess.check_call([
        "git", "commit", "-m",
        f"promote(autoresearch-v2): {rule_id} to live",
    ])


def main(argv: list[str] | None = None) -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--rule-id", required=True)
    ap.add_argument("--pending-path", type=Path,
                    default=DEFAULT_PENDING_PATH)
    ap.add_argument("--no-commit", action="store_true",
                    help="dry run: write files but do not git commit")
    args = ap.parse_args(argv)

    rows = _load_pending(args.pending_path)
    hit = [r for r in rows if r.get("proposal_id") == args.rule_id]
    if not hit:
        print(f"ERROR: rule {args.rule_id} not in "
              f"{args.pending_path}")
        return 2
    rule = hit[0]
    if rule.get("state") != "FORWARD_SHADOW_PASS":
        print(f"ERROR: rule {args.rule_id} state is "
              f"{rule.get('state')!r}, not FORWARD_SHADOW_PASS")
        return 3

    strategy_path = _write_strategy_file(rule, args.rule_id)
    _append_registry_entry(rule, args.rule_id)
    if not args.no_commit:
        _git_commit(strategy_path, args.rule_id)
    print(f"[promote_to_live] {args.rule_id} promoted")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
